// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Alarm describes how an expired timer should sound.
 */
export interface Alarm {
    /**
     * SoundFile is the path to a user-supplied sound. When empty the frontend
     * synthesises a beep instead, so the app always has a working alarm with
     * no bundled audio asset.
     */
    "soundFile": string;

    /**
     * Volume is 0..1.
     */
    "volume": number;

    /**
     * Muted silences the alarm sound; the visual flash still happens.
     */
    "muted": boolean;
}

/**
 * Preset is one of the quick-set buttons.
 */
export interface Preset {
    "label": string;
    "seconds": number;
}
