// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * State is the lifecycle state of a timer.
 */
export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * StateRunning means the timer is counting down towards EndsAtMS.
     */
    StateRunning = "running",

    /**
     * StatePaused means the timer holds a fixed RemainingMS and is not counting.
     */
    StatePaused = "paused",

    /**
     * StateExpired means the timer reached zero. It stays in this state, and
     * keeps alarming, until the user dismisses or restarts it.
     */
    StateExpired = "expired",
};

/**
 * Timer is a single countdown. It is serialised both to the frontend and to the
 * settings file, so the JSON tags are part of two contracts.
 * 
 * EndsAtMS is meaningful only while running; RemainingMS is meaningful only
 * while paused or expired. Keeping both lets a paused timer be persisted without
 * inventing a fake deadline.
 */
export interface Timer {
    "id": string;
    "label": string;
    "totalMs": number;
    "remainingMs": number;
    "endsAtMs": number;
    "state": State;
    "createdMs": number;

    /**
     * Alarming is true from the moment a timer expires until it is dismissed.
     * It is separate from State so that a dismissed timer can stay visible at
     * zero without the alarm restarting whenever the list is re-read.
     */
    "alarming": boolean;

    /**
     * Color is copied from the preset that created this timer, at creation
     * time -- it is not looked up live, so editing or deleting the preset
     * later cannot change the colour of a timer already running. Empty for a
     * timer created without a preset (or one created before this field
     * existed); the frontend falls back to its default colour in that case.
     */
    "color": string;
}
