// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "./internal/settings/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as timer$0 from "./internal/timer/models.js";

/**
 * ChangedEvent is the payload of EventChanged.
 */
export interface ChangedEvent {
    "timers": timer$0.Timer[] | null;
}

/**
 * ExpiredEvent is the payload of EventExpired. Several timers can come due in
 * the same tick — and a long machine sleep can bring a whole batch due at once
 * — so this is always a list.
 */
export interface ExpiredEvent {
    "timers": timer$0.Timer[] | null;
}

/**
 * Preferences is the user-editable part of the settings. Timers are persisted
 * too but are not the user's to edit, so they are kept out of this type.
 */
export interface Preferences {
    "presets": settings$0.Preset[] | null;
    "alarm": settings$0.Alarm;
}
