// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TimerService is the Wails-bound adapter over the countdown engine. It is
 * deliberately thin: scheduling policy and state transitions live in
 * internal/timer, which is testable without a running application.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as timer$0 from "./internal/timer/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateTimer starts a new timer for the given duration. Minutes and seconds
 * are not limited to 59, so a preset of 7200 seconds can be passed straight
 * through without the caller converting it first.
 */
export function CreateTimer(hours: number, minutes: number, seconds: number, label: string): $CancellablePromise<timer$0.Timer> {
    return $Call.ByID(4113711277, hours, minutes, seconds, label);
}

/**
 * DeleteTimer removes a timer.
 */
export function DeleteTimer(id: string): $CancellablePromise<void> {
    return $Call.ByID(871220648, id);
}

/**
 * DismissTimer silences an expired timer but keeps it in the list.
 */
export function DismissTimer(id: string): $CancellablePromise<timer$0.Timer> {
    return $Call.ByID(2804575549, id);
}

/**
 * GetPreferences returns the presets and alarm settings.
 */
export function GetPreferences(): $CancellablePromise<$models.Preferences> {
    return $Call.ByID(3982987350);
}

/**
 * ListTimers returns every timer. The frontend calls this once on mount and
 * then keeps in step through events.
 */
export function ListTimers(): $CancellablePromise<timer$0.Timer[] | null> {
    return $Call.ByID(3512616374);
}

/**
 * PauseTimer freezes a running timer.
 */
export function PauseTimer(id: string): $CancellablePromise<timer$0.Timer> {
    return $Call.ByID(257355547, id);
}

/**
 * PickAlarmFile opens a native file picker and returns the chosen path, or an
 * empty string if the user cancelled.
 */
export function PickAlarmFile(): $CancellablePromise<string> {
    return $Call.ByID(2033512328);
}

/**
 * RestartTimer runs a timer again from its full duration.
 */
export function RestartTimer(id: string): $CancellablePromise<timer$0.Timer> {
    return $Call.ByID(3240039928, id);
}

/**
 * ResumeTimer restarts a paused timer from where it left off.
 */
export function ResumeTimer(id: string): $CancellablePromise<timer$0.Timer> {
    return $Call.ByID(2525166768, id);
}

/**
 * SavePreferences stores new presets and alarm settings and returns them as
 * stored, which may differ from what was sent: out-of-range values are
 * repaired rather than rejected.
 */
export function SavePreferences(p: $models.Preferences): $CancellablePromise<$models.Preferences> {
    return $Call.ByID(2051932637, p);
}
